Clean 10 documents and flag 1 issue
kirsan31/winforms-datavisualization pull request #17
Opened 2022-11-18 04:23 UTC by paul1956

Mostly spelling and formatting issue plus reccommented code fixes but 1 real issue might be in Chart Element.cs and is flagged with review. If its correct leave the Pragma I added. No rush I will have very intermittent internet access for the next 6 weeks starting Saturday.

2022-11-19 18:29 UTC, kirsan31 requested changes

2022-11-19 18:29 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/General/ChartGraphics.cs
> +                    break;
```suggestion
                case HatchBrush br:
                    brushColor = br.BackgroundColor;
                    break;
                case LinearGradientBrush br:
                    brushColor = br.LinearColors[0];
                    break;
                case PathGradientBrush br:
                    brushColor = br.CenterColor;
                    break;
                case SolidBrush br:
                    brushColor = br.Color;
                    break;
```

2022-11-20 00:19 UTC, paul1956 commented on src/System.Windows.Forms.DataVisualization/General/ChartElement.cs
> +#pragma warning restore CA1069 // Enums values should not be duplicated
Is that something I did?

2022-11-20 04:48 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/General/ChartElement.cs
> +#pragma warning restore CA1069 // Enums values should not be duplicated
> Is that something I did?

Yea, this refactoring removed number 100 from the enum 🤷

2022-11-20 04:49 UTC, kirsan31 approved these changes

2022-11-20 04:50 UTC, merged