Cleanup code in WinForms Data Visualization
kirsan31/winforms-datavisualization pull request #6
Opened 2022-10-28 23:17 UTC by paul1956

I did a basic code cleanup (no Logic changes), feel free to ignore/close if you are not interested.

2022-10-29 10:25 UTC, kirsan31 commented
Omg - lots of changes to review  😱 I will look into it, thank you @paul1956.

P.s. have you tried the latest V.S. preview (17.4 P5) in terms of #4? [There is a discussion ](https://github.com/KlausLoeffelmann/NetControlDesigners/pull/9#issuecomment-1293719751)on the topic of the designer with Klaus, I hope we will come to something in the end...

2022-10-29 14:02 UTC, kirsan31 requested changes

2022-10-29 14:02 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/Utilities/XmlSerializer.cs
> +                // 0 - undefined; 1 - '*'; 2 - 'Back*'; 3 - Exact
Lost the meaning of the comments.

2022-10-29 14:02 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/Utilities/XmlSerializer.cs
> +                    // 0 - undefined; 1 - '*'; 2 - 'Back*'; 3 - Exact
Lost the meaning of the comments.

2022-10-30 15:32 UTC, kirsan31 requested changes

2022-10-30 15:32 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/General/Legend.cs
> +this.autofitFont ?? this.Font,
Broken indentation.

2022-10-30 15:32 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/Utilities/XmlSerializer.cs
> +                // 0 - undefined; 1 - '*'; 2 - 'Back*'; 3 - Exact
This comments was for:
`serialzableClassFitType`
and
`serialzablePropertyFitType`

2022-10-30 15:32 UTC, kirsan31 commented on src/System.Windows.Forms.DataVisualization/Utilities/XmlSerializer.cs
> +                    // 0 - undefined; 1 - '*'; 2 - 'Back*'; 3 - Exact
This comments was for:
`nonSerialzableClassFitType`
and
`nonSerialzablePropertyFitType`

2022-10-30 21:25 UTC, paul1956 commented on .gitignore
> +/src/System.Windows.Forms.DataVisualization/ChartWin.csproj
I don't know how; sorry those changes were supported to le local to my machine.

2022-10-30 21:54 UTC, paul1956 commented on .gitignore
> +/src/System.Windows.Forms.DataVisualization/ChartWin.csproj
I figured it out I need to remove the project from my solution so it should happen again.

2022-10-31 07:37 UTC, kirsan31 commented
@paul1956 thank you, we have only this 2 remaining:
https://github.com/kirsan31/winforms-datavisualization/pull/6#discussion_r1008681442
https://github.com/kirsan31/winforms-datavisualization/pull/6#discussion_r1008881965

P.s. I could fix these little things myself if you allowed editing from maintainers when creating the PR.

2022-10-31 08:05 UTC, paul1956 commented on src/System.Windows.Forms.DataVisualization/General/Legend.cs
> +this.autofitFont ?? this.Font,
Fixed

2022-10-31 08:17 UTC, paul1956 commented on src/System.Windows.Forms.DataVisualization/ChartTypes/ColumnChart.cs
> +        drawingOperationType);
fixed

2022-10-31 10:17 UTC, kirsan31 approved these changes

2022-10-31 10:21 UTC, merged

2022-10-31 10:23 UTC, kirsan31 commented
Thanks @paul1956 👍

2022-10-31 20:24 UTC, paul1956 commented
No idea how to do that. My Git experience in limited to what I find in Google and what VS let's me do. I will try to find out how to change today. I skipped doing anything with pattern matching, are you interested in those cleanups?

2022-10-31 20:50 UTC, kirsan31 commented
> No idea how to do that. My Git experience in limited to what I find in Google and what VS let's me do. I will try to find out how to change today. 

I do not quite understand what is at stake. I already merged this PR - everything is fine 👍

Oh, if you are talking about this:

> P.s. I could fix these little things myself if you allowed editing from maintainers when creating the PR.

Then it's just one tick when creating a PR: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

> I skipped doing anything with pattern matching, are you interested in those cleanups?

Thank you, but I think we need to take a break  😂 - it's very tedious to check such a massive code changes (which is why I didn't do it myself in the first place 🙄).