Update Axis.cs without switch and Tuple Swap
kirsan31/winforms-datavisualization pull request #8
Opened 2022-11-01 10:39 UTC by paul1956

using new Branch
Allow edits by maintainers checked

2022-11-02 08:07 UTC, kirsan31 requested changes

2022-11-02 08:16 UTC, kirsan31 commented
P.s. I have checked `Allow edits by maintainers` can be omitted - it's not necessary. Sorry 🙃

2022-11-02 09:11 UTC, paul1956 commented
My experience is the automated fixes are very good, go generally I just accept them. But doubt they understand commented out or ifdef code.

2022-11-02 11:36 UTC, merged

2022-11-03 06:21 UTC, paul1956 commented
@kirsan31 Don't know what is going on but I deleted everything on my machine and cloned https://github.com/dotnet/winforms-datavisualization.git and it will not build.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		C:\Program Files\dotnet\sdk\7.0.100-rc.2.22477.23\Sdks\Microsoft.DotNet.Arcade.Sdk\Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.	ChartWin		3	
Warning	NU1701	Package 'System.Drawing.Common 4.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0'. This package may not be fully compatible with your project.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Error		Project "C:\Users\PaulM\Source\Repos\winforms-datavisualization\packageContent.targets" was not imported by "C:\Users\PaulM\Source\Repos\winforms-datavisualization\Directory.Build.targets" at (4,3), due to the file not existing.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\packageContent.targets	4	
Warning	NU1604	Project dependency Microsoft.NETCore.Platforms does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Warning	NU1604	Project dependency System.Data.SqlClient does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Warning	NU1604	Project dependency System.Drawing.Common does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Warning	NU1604	Project dependency System.Drawing.Primitives does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Warning	NU1604	Project dependency System.Windows.Extensions does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\src\System.Windows.Forms.DataVisualization\ChartWin.csproj	1	
Error	MSB4236	The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.	ChartWin	C:\Users\PaulM\Source\Repos\winforms-datavisualization\Directory.Build.props	3	
Warning		Unable to locate the .NET SDK version '3.0.100-preview4-011144' as specified by global.json, please check that the specified version is installed.	ChartWin		1	
Warning		Unable to locate the .NET SDK version '3.0.100-preview4-011144' as specified by global.json, please check that the specified version is installed.	ChartWin		28	
Warning		Unable to locate the .NET SDK version '3.0.100-preview4-011144' as specified by global.json, please check that the specified version is installed.	ChartWin		154	
Warning		Unable to locate the .NET SDK version '3.0.100-preview4-011144' as specified by global.json, please check that the specified version is installed.	ChartWin		155	
Error		Unable to resolve 'Microsoft.DotNet.Arcade.Sdk (= 1.0.0-beta.19154.3)' for '.NETStandard,Version=v0.0'.	ChartWin		3	
```